### ISSUE TITLE
Establish project roadmap and processes

### ISSUE THREAD

**Issue by ansermino** [ChainSafe/fil-secondary-retrieval-markets#5]
Collaborate with the team to develop a project roadmap that outlines and prioritizes epics. 

- [x] setup initial project roadmap
- [x] collaborate with the team to determine project epics and assign priority
- [x] setup kanban board for sprint planning
- [x] schedule sprint planning and daily standups
